"""add revoked token table for logout

Revision ID: 0575f1576471
Revises: 969d2ce28d35
Create Date: 2026-09-20 15:00:26.207345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '0575f1576471'
down_revision: Union[str, None] = '969d2ce28d35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revoked_token',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('jti', sa.VARCHAR(length=64), nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revoked_token_id'), 'revoked_token', ['id'], unique=False)
    op.create_index(op.f('ix_revoked_token_jti'), 'revoked_token', ['jti'], unique=True)
    op.create_index(op.f('ix_revoked_token_user_id'), 'revoked_token', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_revoked_token_user_id'), table_name='revoked_token')
    op.drop_index(op.f('ix_revoked_token_jti'), table_name='revoked_token')
    op.drop_index(op.f('ix_revoked_token_id'), table_name='revoked_token')
    op.drop_table('revoked_token')
    # ### end Alembic commands ###
