"""add infinitepay payment gateway option

Revision ID: 9ea34282f83f
Revises: 0575f1576471
Create Date: 2026-09-20 15:13:39.610440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '9ea34282f83f'
down_revision: Union[str, None] = '0575f1576471'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment', 'gateway',
               existing_type=mysql.ENUM('mock', 'mercadopago'),
               type_=sa.Enum('mock', 'mercadopago', 'infinitepay', name='paymentgatewayenum'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment', 'gateway',
               existing_type=sa.Enum('mock', 'mercadopago', 'infinitepay', name='paymentgatewayenum'),
               type_=mysql.ENUM('mock', 'mercadopago'),
               existing_nullable=False)
    # ### end Alembic commands ###
