"""add rbac, sections, cart, order, payment and product fields

Revision ID: dbe179e98607
Revises: eeca96c9e14c
Create Date: 2026-06-22 21:48:02.474771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = 'dbe179e98607'
down_revision: Union[str, None] = 'eeca96c9e14c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('section',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=255), nullable=False),
    sa.Column('descricao', sa.TEXT(), nullable=True),
    sa.Column('status', sa.Enum('ativo', 'inativo', name='sectionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_section_id'), 'section', ['id'], unique=False)
    op.create_index(op.f('ix_section_nome'), 'section', ['nome'], unique=False)
    op.create_table('cart',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cart_id'), 'cart', ['id'], unique=False)
    op.create_index(op.f('ix_cart_user_id'), 'cart', ['user_id'], unique=True)
    op.create_table('customer_order',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('adress_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('status', sa.Enum('pendente', 'pago', 'em_separacao', 'enviado', 'entregue', 'cancelado', 'nao_aprovado', name='orderstatus'), nullable=False),
    sa.Column('subtotal', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('desconto', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['adress_id'], ['adress.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_order_adress_id'), 'customer_order', ['adress_id'], unique=False)
    op.create_index(op.f('ix_customer_order_id'), 'customer_order', ['id'], unique=False)
    op.create_index(op.f('ix_customer_order_status'), 'customer_order', ['status'], unique=False)
    op.create_index(op.f('ix_customer_order_user_id'), 'customer_order', ['user_id'], unique=False)
    op.create_table('cart_item',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('cart_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('product_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('quantidade', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cart_item_cart_id'), 'cart_item', ['cart_id'], unique=False)
    op.create_index(op.f('ix_cart_item_id'), 'cart_item', ['id'], unique=False)
    op.create_index(op.f('ix_cart_item_product_id'), 'cart_item', ['product_id'], unique=False)
    op.create_table('order_item',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('order_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('product_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('quantidade', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('preco_unitario', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['customer_order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_item_id'), 'order_item', ['id'], unique=False)
    op.create_index(op.f('ix_order_item_order_id'), 'order_item', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_item_product_id'), 'order_item', ['product_id'], unique=False)
    op.create_table('payment',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('order_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('gateway', sa.Enum('mock', 'mercadopago', name='paymentgatewayenum'), nullable=False),
    sa.Column('forma_pagamento', sa.VARCHAR(length=20), nullable=False),
    sa.Column('status', sa.Enum('pendente', 'aprovado', 'recusado', name='paymentstatus'), nullable=False),
    sa.Column('transaction_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('valor', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['customer_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_id'), 'payment', ['id'], unique=False)
    op.create_index(op.f('ix_payment_order_id'), 'payment', ['order_id'], unique=True)
    op.create_index(op.f('ix_payment_status'), 'payment', ['status'], unique=False)

    # category.section_id is NOT NULL but categorias já podem existir: adiciona como nullable,
    # cria uma seção padrão para backfill e só então aplica a constraint NOT NULL.
    op.add_column('category', sa.Column('section_id', mysql.BIGINT(unsigned=True), nullable=True))
    bind = op.get_bind()
    existing_categories = bind.execute(sa.text("SELECT COUNT(*) FROM category")).scalar()
    if existing_categories:
        result = bind.execute(sa.text(
            "INSERT INTO section (nome, descricao, status, created_at, updated_at) "
            "VALUES ('Geral', 'Seção padrão criada automaticamente para categorias já existentes', 'ativo', NOW(), NOW())"
        ))
        default_section_id = result.lastrowid
        bind.execute(sa.text("UPDATE category SET section_id = :sid WHERE section_id IS NULL"), {"sid": default_section_id})
    op.alter_column('category', 'section_id', existing_type=mysql.BIGINT(unsigned=True), nullable=False)
    op.add_column('category', sa.Column('status', sa.Enum('ativo', 'inativo', name='categorystatus'), server_default='ativo', nullable=False))
    op.create_index(op.f('ix_category_section_id'), 'category', ['section_id'], unique=False)
    op.create_foreign_key(None, 'category', 'section', ['section_id'], ['id'])

    op.add_column('product', sa.Column('preco_promocional', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('product', sa.Column('estoque_minimo', mysql.BIGINT(unsigned=True), server_default='5', nullable=False))
    op.add_column('product', sa.Column('peso', sa.DECIMAL(precision=10, scale=3), nullable=True))
    op.add_column('product', sa.Column('dimensoes', sa.VARCHAR(length=100), nullable=True))
    op.add_column('user', sa.Column('role', sa.Enum('admin', 'cliente', name='userrole'), server_default='cliente', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    op.drop_column('product', 'dimensoes')
    op.drop_column('product', 'peso')
    op.drop_column('product', 'estoque_minimo')
    op.drop_column('product', 'preco_promocional')
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.drop_index(op.f('ix_category_section_id'), table_name='category')
    op.drop_column('category', 'status')
    op.drop_column('category', 'section_id')
    op.drop_index(op.f('ix_payment_status'), table_name='payment')
    op.drop_index(op.f('ix_payment_order_id'), table_name='payment')
    op.drop_index(op.f('ix_payment_id'), table_name='payment')
    op.drop_table('payment')
    op.drop_index(op.f('ix_order_item_product_id'), table_name='order_item')
    op.drop_index(op.f('ix_order_item_order_id'), table_name='order_item')
    op.drop_index(op.f('ix_order_item_id'), table_name='order_item')
    op.drop_table('order_item')
    op.drop_index(op.f('ix_cart_item_product_id'), table_name='cart_item')
    op.drop_index(op.f('ix_cart_item_id'), table_name='cart_item')
    op.drop_index(op.f('ix_cart_item_cart_id'), table_name='cart_item')
    op.drop_table('cart_item')
    op.drop_index(op.f('ix_customer_order_user_id'), table_name='customer_order')
    op.drop_index(op.f('ix_customer_order_status'), table_name='customer_order')
    op.drop_index(op.f('ix_customer_order_id'), table_name='customer_order')
    op.drop_index(op.f('ix_customer_order_adress_id'), table_name='customer_order')
    op.drop_table('customer_order')
    op.drop_index(op.f('ix_cart_user_id'), table_name='cart')
    op.drop_index(op.f('ix_cart_id'), table_name='cart')
    op.drop_table('cart')
    op.drop_index(op.f('ix_section_nome'), table_name='section')
    op.drop_index(op.f('ix_section_id'), table_name='section')
    op.drop_table('section')
    # ### end Alembic commands ###
